### ISSUE TITLE
Docker is crashing

### ISSUE THREAD

**Issue by MTRNord** [jamesyale/docker-ebot-csgo#3]
I get:

```
      ____        _
     |  _ \      | |
  ___| |_) | ___ | |_
 / _ \  _ < / _ \| __|
|  __/ |_) | (_) | |_
 \___|____/ \___/ \__|

PHP Compatibility Test
-----------------------------------------------------
| PHP 5.3.1 or newer    -> required  -> [ Yes ] 5.5.12-2ubuntu4.6
| Standard PHP Library  -> required  -> [ Yes ]
| MySQL                 -> required  -> [ Yes ]
| Sockets               -> required  -> [ Yes ]
-----------------------------------------------------
| Timezone is not set in php.ini. Please edit it and change/set "date.timezone" appropriately. Setting to default: 'UTC'
-----------------------------------------------------
| Registerung Shutdown function !
| Starting eBot Websocket-Server !
| WebSocket server crashed
-----------------------------------------------------
```

I am using Kitematic on Win7 as Host. any Ideas to fix that?

**Comment by jamesyale** [comment]
Guessing this might be the websocket server failing to bind to the expected address - do you know what IP range your docker instances use?

**Comment by MTRNord** [comment]
I am not entirely shure but it is 192.168.99.x or 192.168.x.x but I did not change any configs of your version

**Comment by MTRNord** [comment]
When I run it directly in the vbox it runs (only crash is the missing database)

**Comment by yoberlin** [comment]
I have the same problem on Deb Linux
This is the Dedicated Server

**Comment by jamesyale** [comment]
Apologies for the delay, this is now updated to the latest version of eBot also using a v2 compose file which makes the networking a lot cleaner. 

Should resolve all the issues reported here, if not, please re-open, and if you find any other bugs please open a new issue :)
