### ISSUE TITLE
ERROR: Conflicting options: host type networking can't be used with links. This would result in undefined behavior

### ISSUE THREAD

**Issue by MrPalamen** [jamesyale/docker-ebot-csgo#4]
root@scw-aea460:~# docker-compose up
Starting root_mysql_1
Starting root_ebotweb_1
Creating root_ebot_1
ERROR: Conflicting options: host type networking can't be used with links. This would result in undefined behavior
root@scw-aea460:~#

**Comment by jamesyale** [comment]
I don't see this behaviour with docker-compose version 1.7.0rc1, build 1ad8866 on MacOS. 

It's been a while since I've touched this version but it should be a simple change - I'll make the change and check the app still connects to the SQL database OK.

**Comment by Spiderschwein** [comment]
I can confirm this problem with docker-compose version 1.8.1, build 878cff1, Docker version 1.12.1, build 23cf638 on Ubuntu Trusty.

**Comment by jamesyale** [comment]
Thanks for the report - I'm working on an updated version of this with changed in the underlying application to avoid the requirement for --net=host. 

I'll see if there is a quick fix in the meantime.

**Comment by jamesyale** [comment]
You should find the issues resolved now - we did another LAN party so I updated eBot to the latest version (which is much improved) and rewrote the compose file to version 2 for nicer networking. 

If you find any other bugs please open a new issue, or re-open this one if I missed something :)
