### ISSUE TITLE
Linking Web to / instead of ebot-csgo

### ISSUE THREAD

**Issue by MTRNord** [jamesyale/docker-ebot-csgo#6]
When ebot is linked to ebot-csgo subdir and not to the / directory some files cannot be accesed by eBot. Is there a way to fix that issue in this Dockerfile?

**Comment by jamesyale** [comment]
Yup, it's just a matter of reconfiguring the Apache rewrite rules - I'll have a play with it, it has been on my todo list.

**Comment by MTRNord** [comment]
Thats cool :) Thanks for Info

**Comment by jamesyale** [comment]
Fixed (at last) in https://github.com/jamesyale/docker-ebot-csgo-web/commit/242bb8515c442f8731ff7b903a5c85417fec4862
