### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by Soren90** [jamesyale/docker-ebot-csgo#7]
Hi,

I've been trying for some hours to get the timezone to be correct. I've tried using environment variables to set the timezone correctly, but i can't get it to work.

I get this when i run the compose file:
ebotweb_1  | Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/ebotv3-web/eBot-CSGO-Web/lib/vendor/symfony/lib/config/sfRootConfigHandler.class.php on line 91

Also get an equivalent error on the ebot server.

**Comment by jamesyale** [comment]
Thanks for the report, I set a static timezone value to UTC to avoid the message, will look at making it variable for a future release, or patches welcome. https://github.com/jamesyale/docker-ebot-csgo-web/commit/7dea6e48e4ea67913c0efe76c5a7e5554e6cfabf
